export interface Permissionario {
  id: String
  id_integracao: number
  numero_de_cadastro_antigo: String
  nome_razao_social: String
  tipo: String
  cpf_cnpj: String
  rg: String
  estado_civil: String
  inscricao_municipal: String
  alvara_de_funcionamento: String
  responsavel: String
  procurador_responsavel: String
  telefone: String
  telefone2: String
  celular: String
  email: String
  data_nascimento: Date
  naturalidade: String
  nacionalidade: String
  cnh: String
  categoria_cnh: String
  vencimento_cnh: Date
  atestado_de_saude: boolean
  certidao_negativa: boolean
  validade_certidao_negativa: Date
  comprovante_de_endereco: boolean
  inscricao_do_cadastro_mobiliario: boolean
  numero_do_cadastro_mobiliario: String
  crlv: boolean
  dpvat: boolean
  certificado_pontuacao_cnh: boolean
  classificacao_do_processo: String
  numero_do_processo: String
  data_processo_seletivo: Date
  entidade_associativa_id: String
  modalidade_id: String
  endereco_id: String
}
