export interface Permissionario {
  id: String
  id_integracao: number
  numero_de_cadastro_antigo: String
  nome_razao_social: String
  tipo: String
  cpf_cnpj: String
  rg: String
  estado_civil: String
  inscricao_municipal: String
  alvara_de_funcionamento: String
  responsavel: String
  procurador_responsavel: String
  telefone: String
  telefone2: String
  celular: String
  email: String
  data_nascimento: Date
  naturalidade: String
  nacionalidade: String
  cnh: String
  categoria_cnh: String
  vencimento_cnh: Date
  atestado_de_saude: boolean
  certidao_negativa: boolean
  validade_certidao_negativa: Date
  comprovante_de_endereco: boolean
  inscricao_do_cadastro_mobiliario: boolean
  numero_do_cadastro_mobiliario: String
  curso_primeiro_socorros: boolean
  curso_primeiro_socorros_emissao: Date
  crlv: boolean
  dpvat: boolean
  certificado_pontuacao_cnh: boolean
  contrato_comodato: boolean
  contrato_comodato_validade: boolean
  ipva: boolean
  relacao_dos_alunos_transportados: boolean
  laudo_vistoria_com_aprovacao_da_sa_trans: boolean
  ciretran_vistoria: boolean
  ciretran_autorizacao: boolean
  selo_gnv: boolean
  selo_gnv_validade: Date
  taximetro_tacografo: boolean
  taximetro_tacografo_numero: String
  taximetro_tacografo_afericao: Date
  inicio_atividades: Date
  termino_atividades: Date
  termino_atividades_motivo: String
  data_transferencia: Date
  classificacao_do_processo: String
  numero_do_processo: String
  data_processo_seletivo: Date
  prefixo: String
  inss: String
  entidade_associativa_id: String
  modalidade_id: String
  endereco_id: String
  data_obito: Date
  certidao_de_obito: String
  nome_inventariante: String
  grau_de_paretesco_inventariante: String
  numero_do_processo_do_inventario: String
  parecer_do_juiz_sobre_inventario: String
}
