export interface TipoDaSolicitacao {
  id: String
  nome: String
  nome_campo1: String
  nome_campo2: String
  nome_campo3: String
  nome_campo4: String
  nome_campo5: String
  nome_campo6: String
  nome_campo7: String
  nome_campo8: String
  nome_campo9: String
  nome_campo10: String
  nome_campo11: String
  nome_campo12: String
  nome_campo13: String
  nome_campo14: String
  nome_campo15: String
  nome_campo16: String
  nome_campo17: String
  nome_campo18: String
  nome_campo19: String
  nome_campo20: String
  nome_campo21: String
  nome_campo22: String
  nome_campo23: String
  nome_campo24: String
  nome_campo25: String
  desc_campo1: String
  desc_campo2: String
  desc_campo3: String
  desc_campo4: String
  desc_campo5: String
  desc_campo6: String
  desc_campo7: String
  desc_campo8: String
  desc_campo9: String
  desc_campo10: String
  desc_campo11: String
  desc_campo12: String
  desc_campo13: String
  desc_campo14: String
  desc_campo15: String
  desc_campo16: String
  desc_campo17: String
  desc_campo18: String
  desc_campo19: String
  desc_campo20: String
  desc_campo21: String
  desc_campo22: String
  desc_campo23: String
  desc_campo24: String
  desc_campo25: String
  desc_arquivo1: String
  desc_arquivo2: String
  desc_arquivo3: String
  desc_arquivo4: String
}
