export interface TipoDaSolicitacao {
  id: string
  nome: string
  nome_campo1: string
  nome_campo2: string
  nome_campo3: string
  nome_campo4: string
  nome_campo5: string
  nome_campo6: string
  nome_campo7: string
  nome_campo8: string
  nome_campo9: string
  nome_campo10: string
  nome_campo11: string
  nome_campo12: string
  nome_campo13: string
  nome_campo14: string
  nome_campo15: string
  nome_campo16: string
  nome_campo17: string
  nome_campo18: string
  nome_campo19: string
  nome_campo20: string
  nome_campo21: string
  nome_campo22: string
  nome_campo23: string
  nome_campo24: string
  nome_campo25: string
  desc_campo1: string
  desc_campo2: string
  desc_campo3: string
  desc_campo4: string
  desc_campo5: string
  desc_campo6: string
  desc_campo7: string
  desc_campo8: string
  desc_campo9: string
  desc_campo10: string
  desc_campo11: string
  desc_campo12: string
  desc_campo13: string
  desc_campo14: string
  desc_campo15: string
  desc_campo16: string
  desc_campo17: string
  desc_campo18: string
  desc_campo19: string
  desc_campo20: string
  desc_campo21: string
  desc_campo22: string
  desc_campo23: string
  desc_campo24: string
  desc_campo25: string
  desc_arquivo1: string
  desc_arquivo2: string
  desc_arquivo3: string
  desc_arquivo4: string
}
